### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by chavansourabh** [aniruddhha/mern-stack-671c3ee2bb6345cb844715642f4471c5#4]
How to generate  SSH key ? How to connect vscode /local repo. To  github

**Comment by aniruddhha** [comment]
describe the question ? why do you need SSH key ?

**Comment by chavansourabh** [comment]
To push code to github

**Comment by aniruddhha** [comment]
you can push the code by means of http also, for now dont use ssh for pushing code.
